//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.wer.sc.data.cnfutures.generator.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("com.wer.sc.data.cnfutures.generator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 20040102,20040102.09
        ///20040105,20040105.09
        ///20040106,20040106.09
        ///20040107,20040107.09
        ///20040108,20040108.09
        ///20040109,20040109.09
        ///20040112,20040112.09
        ///20040113,20040113.09
        ///20040114,20040114.09
        ///20040115,20040115.09
        ///20040116,20040116.09
        ///20040129,20040129.09
        ///20040130,20040130.09
        ///20040202,20040202.09
        ///20040203,20040203.09
        ///20040204,20040204.09
        ///20040205,20040205.09
        ///20040206,20040206.09
        ///20040209,20040209.09
        ///20040210,20040210.09
        ///20040211,20040211.09
        ///20040212,20040212.09
        ///20040213,20040213.09
        ///200402 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string DayStartTime_M05 {
            get {
                return ResourceManager.GetString("DayStartTime_M05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 20040106.0859,2820,32,32,60732,2818,1,2820,1,1
        ///20040106.09,2818,20,52,-20,2818,1,2820,2,0
        ///20040106.09,2818,2,54,0,2815,10,2818,4,0
        ///20040106.09,2815,20,74,20,2810,31,2818,4,0
        ///20040106.090016,2815,2,76,0,2811,7,2815,9,1
        ///20040106.090017,2815,2,78,0,2811,7,2815,8,1
        ///20040106.090017,2815,16,94,0,2815,2,2817,2,1
        ///20040106.090018,2815,2,96,0,2815,1,2817,2,0
        ///20040106.090021,2815,2,98,0,2813,5,2815,7,0
        ///20040106.090023,2813,10,108,-10,2812,2,2815,7,0
        ///20040106.090025,2815,8,116,4,2812,2,2815,3,1
        ///20040106.0900 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string TickDataClean_M05_20040106 {
            get {
                return ResourceManager.GetString("TickDataClean_M05_20040106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 20140106.0859,3340,2764,2764,1587572,3340,557,3341,28,0
        ///20140106.09,3339,1818,4582,-72,3339,75,3340,513,0
        ///20140106.09,3340,376,4958,-66,3339,46,3340,325,1
        ///20140106.090001,3340,1668,6626,-90,3338,301,3340,4,1
        ///20140106.090002,3340,66,6692,10,3339,1,3340,1082,1
        ///20140106.090002,3340,24,6716,12,3339,9,3340,1193,1
        ///20140106.090003,3339,98,6814,34,3338,328,3339,225,0
        ///20140106.090003,3339,102,6916,78,3338,331,3339,184,1
        ///20140106.090004,3339,150,7066,-34,3338,322,3339,126,1
        ///20140106.090004,3339,168,7234,-2,3 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string TickDataClean_M05_20140106 {
            get {
                return ResourceManager.GetString("TickDataClean_M05_20140106", resourceCulture);
            }
        }
    }
}
