//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.wer.sc.data.update.cnfutures.test.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("com.wer.sc.data.update.cnfutures.test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 20061229.0859,2392,21170,21170,273268,2392,84,2393,49,0
        ///20061229.090541,2392,8,21178,-8,2392,80,2393,49,0
        ///20061229.090542,2393,10,21188,0,2392,80,2393,47,1
        ///20061229.090543,2393,18,21206,-2,2392,79,2393,39,1
        ///20061229.090545,2393,68,21274,-6,2392,134,2393,25,1
        ///20061229.090546,2393,48,21322,-24,2392,134,2393,1,1
        ///20061229.090547,2393,108,21430,0,2393,49,2394,20,1
        ///20061229.090548,2393,122,21552,0,2392,134,2393,140,0
        ///20061229.090549,2393,104,21656,-2,2392,134,2393,100,1
        ///20061229.09055,2393,10,21666,0,239 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string adjust_m05_20061229 {
            get {
                return ResourceManager.GetString("adjust_m05_20061229", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 20071017.0859,3228,1460,1460,492266,3227,1,3228,134,1
        ///20071017.09,3228,2148,3608,-1776,3228,2,3230,152,1
        ///20071017.09,3228,172,3780,-50,3228,1,3230,155,0
        ///20071017.090001,3228,36,3816,-28,3228,22,3230,155,0
        ///20071017.090001,3229,16,3832,-4,3229,15,3230,158,1
        ///20071017.090002,3228,106,3938,-4,3227,7,3228,11,0
        ///20071017.090003,3228,30,3968,2,3228,35,3230,156,1
        ///20071017.090003,3230,86,4054,62,3229,5,3230,151,1
        ///20071017.090004,3230,38,4092,-16,3228,165,3230,146,1
        ///20071017.090004,3230,222,4314,-6,3228,182,32 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string adjust_m05_20071017 {
            get {
                return ResourceManager.GetString("adjust_m05_20071017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 20050329.0859,2676,708,708,119650,2674,13,2676,30,1
        ///20050329.09,2675,4,712,-4,2675,18,2676,30,0
        ///20050329.09,2675,26,738,-4,2675,5,2676,30,0
        ///20050329.090001,2675,6,744,0,2675,12,2676,30,0
        ///20050329.090002,2675,22,766,0,2675,27,2676,140,0
        ///20050329.090003,2674,94,860,-26,2674,44,2675,4,0
        ///20050329.090003,2676,40,900,-22,2675,3,2676,125,1
        ///20050329.090004,2675,8,908,-6,2675,2,2676,122,0
        ///20050329.090004,2673,244,1152,-178,2673,115,2675,100,0
        ///20050329.090006,2675,26,1178,12,2674,19,2675,96,1
        ///20050329.09000 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string adjust_m08_20050329 {
            get {
                return ResourceManager.GetString("adjust_m08_20050329", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 20070531.0859,2548,1294,1294,384296,2547,3,2548,49,1
        ///20070531.09,2548,0,1294,0,2547,3,2548,49,0
        ///20070531.09,2548,86,1380,-24,2546,151,2547,4,1
        ///20070531.090001,2548,350,1730,14,2548,17,2550,40,1
        ///20070531.090001,2548,14,1744,-8,2548,10,2549,2,0
        ///20070531.090002,2550,84,1828,16,2549,4,2550,1,1
        ///20070531.090002,2550,4,1832,-2,2550,302,2551,32,1
        ///20070531.090003,2550,10,1842,6,2550,343,2551,32,0
        ///20070531.090003,2550,10,1852,6,2550,465,2551,32,0
        ///20070531.090004,2550,52,1904,-26,2550,548,2551,9,0
        ///20070531.0 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string adjust_m09_20070531 {
            get {
                return ResourceManager.GetString("adjust_m09_20070531", resourceCulture);
            }
        }
    }
}
