//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.wer.sc.data.test.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("com.wer.sc.data.test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 日期,时间,成交价,成交量,总量,属性(持仓增减),B1价,B1量,B2价,B2量,B3价,B3量,S1价,S1量,S2价,S2量,S3价,S3量,BS
        ///2014-12-29,21:00:04,3453.0,4,4,2410,3452.0,10,0,0,0,0,3459.0,1,0,0,0,0,B
        ///2014-12-29,21:00:28,3454.0,2,6,2,3454.0,2,0,0,0,0,3455.0,1,0,0,0,0,B
        ///2014-12-29,21:00:31,3457.0,4,10,2,3455.0,4,0,0,0,0,3461.0,1,0,0,0,0,B
        ///2014-12-29,21:00:56,3462.0,2,12,0,3462.0,2,0,0,0,0,3463.0,5,0,0,0,0,B
        ///2014-12-29,21:00:57,3462.0,4,16,2,3461.0,3,0,0,0,0,3462.0,3,0,0,0,0,B
        ///2014-12-29,21:01:06,3463.0,4,20,0,3462.0,3,0,0,0,0,3463.0,1,0,0,0,0,B
        ///2014-1 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string AG05_20141230 {
            get {
                return ResourceManager.GetString("AG05_20141230", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 aX01,aX01,20040102,1,aX,DL
        ///aX05,aX05,20040102,5,aX,DL
        ///aX09,aX09,20040102,9,aX,DL
        ///aY01,aY01,20040102,1,aY,DL
        ///aY05,aY05,20040102,5,aY,DL
        ///aY09,aY09,20040317,9,aY,DL
        ///m01,m01,20040102,1,m,DL
        ///m05,m05,20040102,5,m,DL
        ///m09,m09,20040102,9,m,DL
        ///c01,c01,20040922,1,c,DL
        ///c05,c05,20040922,5,c,DL
        ///c09,c09,20040922,9,c,DL
        ///y01,y01,20060109,1,y,DL
        ///y05,y05,20060109,5,y,DL
        ///y09,y09,20060109,9,y,DL
        ///l01,l01,20070731,1,l,DL
        ///l05,l05,20070731,5,l,DL
        ///l09,l09,20070919,9,l,DL
        ///p01,p01,20071029,1,p,DL
        ///p05,p05,20071029,5, [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string codes {
            get {
                return ResourceManager.GetString("codes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2000/07/17,2160,2160,1996,1996,372.00,270.00
        ///2000/07/18,2013,2146,2013,2038,1084.00,692.00
        ///2000/07/19,2040,2040,2011,2012,136.00,742.00
        ///2000/07/20,2021,2026,2006,2016,60.00,742.00
        ///2000/07/21,1990,1998,1970,1970,204.00,754.00
        ///2000/07/24,1970,1977,1930,1976,118.00,748.00
        ///2000/07/25,1938,1998,1937,1998,124.00,748.00
        ///2000/07/26,1990,1990,1940,1950,62.00,748.00
        ///2000/07/27,1987,1987,1935,1948,66.00,748.00
        ///2000/07/28,1924,1950,1922,1926,158.00,742.00
        ///2000/07/31,1950,1958,1940,1948,708.00,742.00
        ///2000/08/ [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string DLm05 {
            get {
                return ResourceManager.GetString("DLm05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日期,时间,成交价,成交量,总量,属性(持仓增减),B1价,B1量,B2价,B2量,B3价,B3量,S1价,S1量,S2价,S2量,S3价,S3量,BS
        ///2013-12-31,8:59:00,3711,192,192,28132,3711,8,0,0,0,0,3721,1,0,0,0,0,S
        ///2013-12-31,9:00:06,3718,8,200,-8,3715,1,0,0,0,0,3718,6,0,0,0,0,B
        ///2013-12-31,9:00:13,3718,18,218,-14,3718,2,0,0,0,0,3720,2,0,0,0,0,B
        ///2013-12-31,9:00:13,3720,4,222,-4,3720,8,0,0,0,0,3722,1,0,0,0,0,B
        ///2013-12-31,9:00:17,3722,2,224,-2,3722,79,0,0,0,0,3725,201,0,0,0,0,B
        ///2013-12-31,9:00:19,3725,16,240,-16,3722,81,0,0,0,0,3725,193,0,0,0,0,B
        ///2013-12-31,9:00:23,3725 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string m01_20131231 {
            get {
                return ResourceManager.GetString("m01_20131231", resourceCulture);
            }
        }
    }
}
