//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.wer.sc.mockdata.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("com.wer.sc.mockdata.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 AMI,豆一连续,A
        ///AX01,豆一01,A
        ///AX03,豆一03,A
        ///AX05,豆一05,A
        ///AX07,豆一07,A
        ///AX09,豆一09,A
        ///AX11,豆一11,A
        ///AX13,豆一指数,A
        ///AY01,豆一01,A
        ///AY03,豆一03,A
        ///AY05,豆一05,A
        ///AY07,豆一07,A
        ///AY09,豆一09,A
        ///AY11,豆一11,A
        ///BMI,豆二连续,B
        ///B01,豆二01,B
        ///B03,豆二03,B
        ///B05,豆二05,B
        ///B07,豆二07,B
        ///B09,豆二09,B
        ///B11,豆二11,B
        ///B13,豆二指数,B
        ///BBMI,胶合板连续,BB
        ///BB01,胶合板01,BB
        ///BB02,胶合板02,BB
        ///BB03,胶合板03,BB
        ///BB04,胶合板04,BB
        ///BB05,胶合板05,BB
        ///BB06,胶合板06,BB
        ///BB07,胶合板07,BB
        ///BB08,胶合板08,BB
        ///BB09,胶合板09,BB
        ///BB10,胶合板10,BB
        ///BB11,胶合板11,BB
        ///BB12,胶合板12,BB
        ///BB13,胶合板指数,BB
        ///CMI,玉米连续,C
        ///C01,玉米01,C
        ///C [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string MockData_Code {
            get {
                return ResourceManager.GetString("MockData_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 20040102,20040102.09
        ///20040105,20040105.09
        ///20040106,20040106.09
        ///20040107,20040107.09
        ///20040108,20040108.09
        ///20040109,20040109.09
        ///20040112,20040112.09
        ///20040113,20040113.09
        ///20040114,20040114.09
        ///20040115,20040115.09
        ///20040116,20040116.09
        ///20040129,20040129.09
        ///20040130,20040130.09
        ///20040202,20040202.09
        ///20040203,20040203.09
        ///20040204,20040204.09
        ///20040205,20040205.09
        ///20040206,20040206.09
        ///20040209,20040209.09
        ///20040210,20040210.09
        ///20040211,20040211.09
        ///20040212,20040212.09
        ///20040213,20040213.09
        ///200402 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string MockData_DayStartTime {
            get {
                return ResourceManager.GetString("MockData_DayStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 20040102
        ///20040105
        ///20040106
        ///20040107
        ///20040108
        ///20040109
        ///20040112
        ///20040113
        ///20040114
        ///20040115
        ///20040116
        ///20040129
        ///20040130
        ///20040202
        ///20040203
        ///20040204
        ///20040205
        ///20040206
        ///20040209
        ///20040210
        ///20040211
        ///20040212
        ///20040213
        ///20040216
        ///20040217
        ///20040218
        ///20040219
        ///20040220
        ///20040223
        ///20040224
        ///20040225
        ///20040226
        ///20040227
        ///20040301
        ///20040302
        ///20040303
        ///20040304
        ///20040305
        ///20040308
        ///20040309
        ///20040310
        ///20040311
        ///20040312
        ///20040315
        ///20040316
        ///20040317
        ///20040318
        ///20040319
        ///20040322
        ///20040323
        ///20040324
        ///20 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string MockData_OpenDate {
            get {
                return ResourceManager.GetString("MockData_OpenDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 20140106.0859,3340,2764,2764,1587572,3340,557,3341,28,0
        ///20140106.09,3339,1818,4582,-72,3339,75,3340,513,0
        ///20140106.09,3340,376,4958,-66,3339,46,3340,325,1
        ///20140106.090001,3340,1668,6626,-90,3338,301,3340,4,1
        ///20140106.090002,3340,66,6692,10,3339,1,3340,1082,1
        ///20140106.090002,3340,24,6716,12,3339,9,3340,1193,1
        ///20140106.090003,3339,98,6814,34,3338,328,3339,225,0
        ///20140106.090003,3339,102,6916,78,3338,331,3339,184,1
        ///20140106.090004,3339,150,7066,-34,3338,322,3339,126,1
        ///20140106.090004,3339,168,7234,-2,3 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string MockData_Tick {
            get {
                return ResourceManager.GetString("MockData_Tick", resourceCulture);
            }
        }
    }
}
